version: '3.8'
services:
  crypto-org-chain-validator0:
    image: local-cro-chain/crypto-org-chain
    container_name: local-cro-chain-crypto-org-chain-validator0
    ports:
      - "26650:26657"
      - "1310:1317"
      - "9090:9090"
      - "8090:26660"
    command: ["start"]
    volumes:
      - ./runtime/crypto-org-chain/validator0:/app
  crypto-org-chain-validator1:
    image: local-cro-chain/crypto-org-chain
    container_name: local-cro-chain-crypto-org-chain-validator1
    ports:
      - "26651:26657"
      - "1311:1317"
      - "9091:9090"
      - "8091:26660"
    command: ["start"]
    volumes:
      - ./runtime/crypto-org-chain/validator1:/app
  cronos-validator0:
    image: local-cro-chain/cronos
    container_name: local-cro-chain-cronos-validator0
    ports:
      - "26652:26657"
      - "1312:1317"
      - "9092:9090"
      - "8092:26660"
      - "8542:8545"
    command: ["start"]
    volumes:
      - ./runtime/cronos/validator0:/app
  cronos-validator1:
    image: local-cro-chain/cronos
    container_name: local-cro-chain-cronos-validator1
    ports:
      - "26653:26657"
      - "1313:1317"
      - "9093:9090"
      - "8093:26660"
      - "8543:8545"
    command: ["start"]
    volumes:
      - ./runtime/cronos/validator1:/app
